name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 4.3.1
repository: https://github.com/TarekkMA/markdown_quill
publish_to: none 

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill: 
    git:
      url: 'git@codeup.aliyun.com:631aaa75f9861067e4e840b5/suji/suji_frontend/suji_flutter_quill_macos.git'
      # ref: '10d17b7d81a3dcc546927788c4aa8bcf0a051437'
      ref: 'e6aff04a3923a691b5b949c458533a2fed388eb1'

  markdown: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  very_good_analysis: ^5.1.0
